--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/DaisukeDaisukeTeam/CustomEntityLoader
build-by-default: true
branches:
- main
projects:
  CustomEntityLoader:
    path: ""
    libs:
      - src: muqsit/simplepackethandler/SimplePacketHandler
        version: ^0.1.0
...
